version: '3.3'
services:
  temp-sensor:
    build: .
    restart: always
    container_name: temp-sensor
    privileged: true
    volumes:
      - ./src:/srv/package/src
      - ./config.json:/srv/package/config.json
    devices:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - 'ZONE_NAME=Living Room'
      - 'ZONE_DESCRIPTION=Living Room'
      - CONTEXT_ROOT=/api
      - APP_PORT=8080
      - TEMPERATURE_SENSOR_PIN=2
      - REPORT_INTERVAL_SECONDS=10
      - CHECK_INTERVAL_SECONDS=5
      - HEATING_CONTROLLER_TYPE=gpio
      - HEATING_CONTROLLER_PIN=16
      - HEATING_CONTROLLER_INVERTED_LOGIC=false
      - COOLING_CONTROLLER_TYPE=wemo
      - COOLING_CONTROLLER_HOST=192.168.2.203
      - COOLING_CONTROLLER_PORT=49153
    command: ts-node ./src/app.ts -c config.json
    # tty: true
